sudo: required

language: ruby

services:
 - docker
 
before_install:
 - docker build -t simtool .
 - docker run --privileged --rm=false -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD -w $PWD simtool ./test


